/* C extension for fibo.
This file in generated by Rubex. Do not change!
*/
#include <ruby.h>
#include <stdint.h>
VALUE __rubex_rb_f_Fibonnaci_compute (int argc,VALUE* argv,VALUE __rubex_arg_self);

VALUE __rubex_rb_f_Fibonnaci_compute (int argc,VALUE* argv,VALUE __rubex_arg_self)
{
  int __rubex_arg_n;
  int __rubex_v_i;
  int __rubex_v_prev;
  int __rubex_v_current;
  int __rubex_v_temp;
  if (argc != 1)
  {
    rb_raise(rb_eArgError, "Need 1 args, not %d", argc);
  }
  __rubex_arg_n=NUM2INT(argv[0])  ;
  __rubex_v_i = (int)(0);
  __rubex_v_prev = (int)(1);
  __rubex_v_current = (int)(1);
  while (( __rubex_v_i < __rubex_arg_n ))
  {

    /* Rubex file location: /home/sameer/gitrepos/scratch/ruby_shizzle/fibo.rubex:9 */
    __rubex_v_temp = __rubex_v_current;

    /* Rubex file location: /home/sameer/gitrepos/scratch/ruby_shizzle/fibo.rubex:10 */
    __rubex_v_current = ( __rubex_v_current + __rubex_v_prev );

    /* Rubex file location: /home/sameer/gitrepos/scratch/ruby_shizzle/fibo.rubex:11 */
    __rubex_v_prev = __rubex_v_temp;

    /* Rubex file location: /home/sameer/gitrepos/scratch/ruby_shizzle/fibo.rubex:12 */
    printf("%s%d%s%d%s", "Number: ", __rubex_v_i, " is ", __rubex_v_current, "\n");

    /* Rubex file location: /home/sameer/gitrepos/scratch/ruby_shizzle/fibo.rubex:14 */
    __rubex_v_i = ( __rubex_v_i + 1 );
  }
}

void Init_fibo ();
void Init_fibo ()
{
  VALUE __rubex_rb_cls_Fibonnaci;

  __rubex_rb_cls_Fibonnaci = rb_define_class("Fibonnaci", rb_cObject);

  rb_define_method(__rubex_rb_cls_Fibonnaci ,"compute", __rubex_rb_f_Fibonnaci_compute, -1);
}
